# action.yml
name: 'Helm-dependabot'
description: 'Greet someone and record the time'
inputs: 
  path: 
    description: "The path of the helm chart"
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.path }}